### ISSUE TITLE
Show graph for formulas not yet installed?

### ISSUE THREAD

**Issue by asmod3us** [martido/homebrew-graph#11]
Hi, is it possible at all to show dependencies of formulas or casks that are not installed yet? `brew deps` does not seem to provide this...

**Comment by martido** [comment]
Hi @asmod3us, sorry for the late reply. Would you like to get a correct dependency graph for any arbitrary formula?

If yes, Homebrew provides one way to get that: `brew deps --tree openssh`. This gives

```
openssh
├── ldns
│   ├── openssl@1.1
│   └── python@3.9
│       ├── gdbm
│       ├── mpdecimal
│       ├── openssl@1.1
│       ├── readline
│       ├── sqlite
│       │   └── readline
│       └── xz
├── libfido2
│   ├── libcbor
│   └── openssl@1.1
└── openssl@1.1
```

brew-graph, unfortunately, does the wrong thing:`brew graph openssh` gives

```
digraph G {
  "openssh";
  "gdbm";
  "ldns";
  "libcbor";
  "libfido2";
  "mpdecimal";
  "openssl@1.1";
  "python@3.9";
  "readline";
  "sqlite";
  "xz";
  "openssh" -> "gdbm";
  "openssh" -> "ldns";
  "openssh" -> "libcbor";
  "openssh" -> "libfido2";
  "openssh" -> "mpdecimal";
  "openssh" -> "openssl@1.1";
  "openssh" -> "python@3.9";
  "openssh" -> "readline";
  "openssh" -> "sqlite";
  "openssh" -> "xz";
}
```

This is clearly wrong because all dependencies are considered first-level dependencies. This is because brew-graph is using just `brew deps --for-each openssh` internally, which doesn't distinguish between levels. The output is:

`openssh: gdbm ldns libcbor libfido2 mpdecimal openssl@1.1 python@3.9 readline sqlite xz`

What brew-graph could do instead is `brew deps openssh -1` to get the first level dependencies and recursively go down to the leaves. Might be worth adding ...

**Comment by martido** [comment]
I've updated the script to create the correct dependency graphs of arbitrary formulae arguments (they don't have to be installed). Feel free to check it out: https://github.com/martido/homebrew-graph/tree/fix-formulae-graph

**Comment by martido** [comment]
If you still have a comment or feedback, please let me know. Closing this issue for now.
